### ISSUE TITLE
How is this repo related to mlgmp

### ISSUE THREAD

**Issue by andrejbauer** [ytomino/gmp-ocaml#2]
I am looking for MPFR binding for OCaml. In OPAM there is [David Monniaux](http://www-verimag.imag.fr/~monniaux/)'s implementation [mlgmp](https://opam.ocaml.org/packages/mlgmp/). Is there a significant difference between this repo and the other one?

**Comment by ytomino** [comment]
His implementation is excellent and still widely used, seems to be unmaintained now, still, it's no problem because GMP and MPFR are enough stable.
I borrowed his idea(pretty printer, streaming format, etc) and the examples (into `examples/mlgmp`).

Supporting MPC is one of the few difference.
And it is using new functions of GMP and MPFR until 2012, like `mpfr_frexp`. Those are not many.
Other, the functor to fix non-default precision/rounding is in the signature of my MPFR binding.

Mine is basically "reinventing the wheel" and had not been used widely. Probably you can use mlgmp with little difficulties less than mine.

**Comment by andrejbauer** [comment]
Many thanks for the explanation. You could investigate whether David's intterested in sharing the reponsibilitirs, or just give them away :-)
